'use strict';
const patients=[
{id:'P-001',name:'Laura Martínez',birth:'1988-05-12',weight:72,height:165,diagnoses:['Diabetes tipo 2'],allergies:['Leche'],incompatible:[],kcal:1800,family:'Antecedente familiar de diabetes tipo 2'},
{id:'P-002',name:'Carlos Ramírez',birth:'1971-09-20',weight:84,height:175,diagnoses:['Hipertensión'],allergies:['Pescado','Frutos secos'],incompatible:[],kcal:2000,family:'Antecedente familiar de hipertensión'},
{id:'P-003',name:'Ana Torres',birth:'1994-02-17',weight:58,height:160,diagnoses:['Celiaquía'],allergies:[],incompatible:['Gluten'],kcal:1800,family:'Sin antecedentes registrados'},
{id:'P-004',name:'Diego López',birth:'1990-01-10',weight:75,height:178,diagnoses:[],allergies:[],incompatible:[],kcal:2000,family:'Sin antecedentes registrados'},
{id:'P-005',name:'Valentina Ríos',birth:'1983-07-24',weight:68,height:164,diagnoses:['Dislipidemia'],allergies:['Frutos secos'],incompatible:[],kcal:1800,family:'Antecedente familiar de dislipidemia'},
{id:'P-006',name:'Andrés Moreno',birth:'1997-11-08',weight:70,height:176,diagnoses:['Anemia ferropénica'],allergies:['Huevo'],incompatible:[],kcal:2200,family:'Sin antecedentes registrados'}];
const foods={arroz:{name:'Arroz integral',tags:[]},pollo:{name:'Pollo',tags:[]},verduras:{name:'Verduras',tags:[]},aceite:{name:'Aceite de oliva',tags:[]},yogur:{name:'Yogur natural',tags:['Leche']},avena:{name:'Avena con gluten',tags:['Gluten']},pescado:{name:'Pescado',tags:['Pescado']},nueces:{name:'Nueces',tags:['Frutos secos']},quinoa:{name:'Quinoa',tags:[]},lentejas:{name:'Lentejas',tags:[]},fruta:{name:'Fruta',tags:[]},huevo:{name:'Huevo',tags:['Huevo']},garbanzos:{name:'Garbanzos',tags:[]},res:{name:'Carne de res magra',tags:[]},espinaca:{name:'Espinaca',tags:[]},naranja:{name:'Naranja',tags:[]},papa:{name:'Papa',tags:[]},aguacate:{name:'Aguacate',tags:[]}};
const diets=[
{id:'D01',name:'Control glucémico sin lácteos',type:'CONTROL DE CARBOHIDRATOS',indications:['Diabetes tipo 2'],kcal:1800,foods:['arroz','pollo','verduras','aceite'],contra:[],definition:'Menú con distribución de carbohidratos en cinco tiempos y exclusión de lácteos.'},
{id:'D02',name:'Control glucémico tradicional',type:'CONTROL DE CARBOHIDRATOS',indications:['Diabetes tipo 2'],kcal:1800,foods:['avena','yogur','pollo','verduras'],contra:[],definition:'Menú con cereales, lácteos y proteína distribuida durante el día.'},
{id:'D03',name:'Vegetal equilibrada',type:'ALIMENTACIÓN VEGETAL',indications:['Diabetes tipo 2','Hipertensión'],kcal:1600,foods:['lentejas','quinoa','verduras','fruta'],contra:[],definition:'Menú basado en legumbres, cereales, frutas y verduras.'},
{id:'D04',name:'Patrón mediterráneo',type:'VARIEDAD ALIMENTARIA',indications:['Diabetes tipo 2','Hipertensión'],kcal:2000,foods:['pescado','nueces','verduras','aceite'],contra:[],definition:'Menú con pescado, frutos secos, vegetales y aceite de oliva.'},
{id:'D05',name:'Plan hiposódico',type:'CONTROL DE SODIO',indications:['Hipertensión'],kcal:2000,foods:['arroz','pollo','verduras','fruta'],contra:[],definition:'Menú con selección de alimentos sin sal añadida.'},
{id:'D06',name:'Plan sin gluten',type:'EXCLUSIÓN DE GLUTEN',indications:['Celiaquía'],kcal:1800,foods:['quinoa','pollo','verduras','fruta'],contra:[],definition:'Menú con ingredientes etiquetados sin gluten en este catálogo.'},
{id:'D07',name:'Plan de cereales mixtos',type:'CEREALES Y LÁCTEOS',indications:['Celiaquía'],kcal:1800,foods:['avena','yogur','fruta'],contra:['Celiaquía'],definition:'Menú de cereales y lácteos con gluten. Revisar las contraindicaciones antes de asignar.'},
{id:'D08',name:'Plan de grasas insaturadas',type:'CONTROL DE LÍPIDOS',indications:['Dislipidemia'],kcal:1800,foods:['aguacate','aceite','pollo','arroz','verduras'],contra:[],definition:'Menú con aguacate, aceite de oliva, cereales y proteína magra.'},
{id:'D09',name:'Mediterránea con frutos secos',type:'PATRÓN MEDITERRÁNEO',indications:['Dislipidemia'],kcal:1900,foods:['pescado','nueces','verduras','aceite','fruta'],contra:[],definition:'Menú que combina pescado, frutos secos, vegetales y aceite de oliva.'},
{id:'D10',name:'Legumbres y fibra',type:'ALTO APORTE DE FIBRA',indications:['Dislipidemia'],kcal:1750,foods:['garbanzos','lentejas','arroz','verduras','fruta'],contra:[],definition:'Menú de legumbres, cereales integrales, frutas y verduras.'},
{id:'D11',name:'Plan con fuentes de hierro',type:'APORTE DE HIERRO',indications:['Anemia ferropénica'],kcal:2200,foods:['res','lentejas','espinaca','naranja','papa'],contra:[],definition:'Menú con carne magra, legumbres, vegetales y fruta.'},
{id:'D12',name:'Ovolactovegetariana',type:'ALIMENTACIÓN OVOLACTOVEGETARIANA',indications:['Anemia ferropénica'],kcal:2100,foods:['huevo','yogur','lentejas','espinaca','naranja'],contra:[],definition:'Menú sin carnes que incluye huevo, lácteos, legumbres y vegetales.'},
{id:'D13',name:'Legumbres sin huevo',type:'ALIMENTACIÓN SIN HUEVO',indications:['Anemia ferropénica'],kcal:2150,foods:['garbanzos','lentejas','quinoa','espinaca','naranja'],contra:[],definition:'Menú de legumbres y quinoa con verduras y fruta, sin huevo entre sus componentes.'}
].map(d=>({...d,intake:'5 ingestas diarias',route:'Oral',duration:'14 días; revisión posterior',dose:'Porciones por definir en consulta',schedule:'Desayuno, media mañana, almuerzo, merienda y cena',supplements:'No registrados'}));
function evaluate(p,d){const associated=p.diagnoses.filter(x=>d.indications.includes(x));const conflicts=[];for(const f of d.foods)for(const a of [...new Set([...p.allergies,...p.incompatible])])if(foods[f].tags.includes(a))conflicts.push(`${foods[f].name} contiene ${a} (${p.allergies.includes(a)?'alergia':'incompatibilidad'} registrada)`);for(const c of d.contra)if(p.diagnoses.includes(c))conflicts.push(`Contraindicación por diagnóstico: ${c}`);const coverage=p.diagnoses.length?associated.length/p.diagnoses.length:0;const caloric=Math.max(0,1-Math.abs(d.kcal-p.kcal)/p.kcal);return{associated:associated.length>0,conflicts,blocked:conflicts.length>0,score:Math.round(70*coverage+30*caloric),coverage:Math.round(70*coverage),caloric:Math.round(30*caloric)};}
if(typeof module!=='undefined')module.exports={patients,diets,evaluate};
